---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: Step 1
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Step 2
      become: yes
      yum: name=MariaDB-client update_cache=yes state=present

    - name: Step 6
      unarchive: src=db/db.tgz dest=~/ mode=0700

    - name: Step 7
      command: ./make_databases.sh {{ db_password }} i-luv-devops.cxlsnpf2csir.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True
